### ISSUE TITLE
GCing an active but failing endpoint is counterproductive

### ISSUE THREAD

**Issue by juliatuttle** [w3c/reporting#23] opened 2016-11-01 01:20 UTC
The garbage collection section of the spec suggests that implementations garbage collect endpoints that have had a certain number of successive failures in a row.

If the endpoint is used by origins that the user is actively interacting with, however, subsequent requests will recreate the endpoint. The net result of this is that any exponential backoff mechanism is reset cyclically instead of continuing to back off as more requests fail.

I suggest removing this section of the garbage collection algorithm; I may open a pull request to do so.

**Comment by igrigorik** [comment] 2016-11-01 22:49
👍

**Comment by RByers** [comment] 2017-03-28 19:16
On the PR @igrigorik asks: 

> Meta question: so, how/where do we run some form of garbage collection? I don't think we want to accumulate reports indefinitely..

I agree this is a problem.  Can we expire old reports instead of trying to expire endpoints?

**Comment by patrickkettner** [comment] 2017-11-11 22:33
@RByers 

> I agree this is a problem. Can we expire old reports instead of trying to expire endpoints?

That seems to be the expected behavior as of our last conversation, no

**Comment by clelland** [comment] 2021-02-24 18:13
Closing this now; please re-open if the fix doesn't completely address the issue.

**Closed** 2021-02-24 18:12 UTC
Labels: report-delivery
