### ISSUE TITLE
endpoints should be stateless

### ISSUE THREAD

**Issue by bakulf** [w3c/reporting#133] opened 2018-11-19 08:26 UTC
Let' say that at t0, for origin X, the browser receives a Report-To header. The following steps are executed:

3.2.6.4 Let endpoint be a new endpoint whose properties are set as follows: [...] retry_after: null
3.2.8 If there is already an entry in the reporting cache for origin, replace it with client. Otherwise, insert client into the reporting cache for origin.

At t1, the browser starts the sending of reports, but the chosen endpoint fails the delivering:
4.5. Attempt to deliver reports to endpoint
4.5.8 Return "Failure".
4.4.3. [...] Otherwise (if result is "Failure"): Increment endpoint’s failures. Set endpoint’s retry_after to a point in the future which the user agent chooses.

At t2, a new Report-To header is received from the same origin X and the browser execs again:
3.2.8 If there is already an entry in the reporting cache for origin, replace it with client. Otherwise, insert client into the reporting cache for origin.

The retry_after is null again. Basically, if the server sends Report-To often the `retry_after`, `failures` and `pending` are useless.  Is this the expected behavior?

**Comment by dcreager** [comment] 2018-11-19 13:29
Hi Andrea, thanks for reporting (har har) this!

That isn't the expected behavior; I think this wording is something I missed in a refactoring I did awhile ago (#67).

I'll take a stab at some new spec language to clarify the intended behavior.  The short version is that `retry_after` etc should **not** be reset if the user agent receives the same configuration that they already had for the origin.  If the user agent receives a **new** configuration for the origin (we'll hammer out on the PR with the spec edits precisely what that means), then the delivery fields would be reset.

**Comment by dcreager** [comment] 2018-11-20 19:15
I'm not a fan of moving `retry_after` and `attempts` to reports.  Those fields are there to support the failover logic, and for that, it's the *endpoint* that has failed and needs to be taken out of rotation (by marking it as "pending").  That tells me that these fields really do belong to the endpoints, not to the individual reports.  (I also think that your proposal would cause us to "lock in" our choice of an endpoint for each report, even if that endpoint has failed; the current text re-runs the "pick an endpoint" algorithm every time we try to upload the report, which ensures that we fail over to another endpoint for the next delivery attempt.)

I'm also not sure I agree that your second example is a problem.  I definitely agree that we should fix your first example — if the server keeps delivering the *same* `Report-To` header, but the delivery fields keep getting reset, I think that's clearly not the desired behavior.

If the server decides to deliver a *different* `Report-To` header, though, I think it's okay (even desirable) for that to be a "reset the world" event (for this origin).  If the server administrator has gone through the effort to configure a new Reporting policy, they probably *want* all of the user agents to retry all of the endpoints that they've just configured.  And if any of them are still bad, the user agents will detect that soon enough and take them back out of rotation.

(All of that assumes that servers will typically deliver the same policy headers in the steady state, and that changing your policy will be a rare event.  I'm happy to call that out explicitly as an assumption, if that would help!)

**Closed** 2022-06-20 13:54 UTC
